### ISSUE TITLE
Adding a Train Tracking App to the Repository

### ISSUE THREAD

**Issue by pooranjoyb** [Web-Dev-for-Beginners/HTML-CSS-and-JavaScript-Projects#15]
# Train Tracking Application
## Description

My goal with this project is to build an **Indian
Train Tracking Application** that will fetch
information about the train status, class,
running dates, etc from an API and serve them
in the frontend.
An express server will be used for hosting the
Application.

## How could it be implemented/designed?
- Creating the basic Frontend using Bootstrap
- Setting up NodeJs and listening it to an Express port
- Connecting frontend with backend
- Setting up the API and fetching information from the API
- Serving fetching data in Frontend
- Documenting the Project

## Please add the DWOC label @LiQuiD-404 

![image](https://user-images.githubusercontent.com/90945182/216651109-19f71bde-52f8-4459-8910-68ab15fd5f2d.png)

**Comment by LiQuiD-404** [comment]
@pooranjoyb Assigned you the issue. Best of Luck.

**Comment by pooranjoyb** [comment]
Getting into it ASAP! :) @LiQuiD-404

**Comment by pooranjoyb** [comment]
Am I allowed to use Github Submodule for the Event or I have to Upload the Project Folder itself in your Repository? @LiQuiD-404
